export const sampleInput = {
  today: "2026-08-10",
  planningDays: 7,
  settings: {
    planningBufferRatio: 0.8,
    softEndTime: "21:30",
    hardStopTime: "22:20",
    nearStartLockMinutes: 30,
  },
  scheduleTemplates: [
    {
      id: "commute-am",
      weekday: 1,
      startTime: "07:20",
      endTime: "08:05",
      context: "mobile",
      focusLevel: "medium",
      extendable: false,
      label: "往路通学",
      active: true,
    },
    {
      id: "lunch",
      weekday: 1,
      startTime: "12:30",
      endTime: "12:55",
      context: "mobile",
      focusLevel: "low",
      extendable: false,
      label: "昼休み",
      active: true,
    },
    {
      id: "evening-desk",
      weekday: 1,
      startTime: "19:20",
      endTime: "21:40",
      context: "desk",
      focusLevel: "high",
      extendable: true,
      label: "帰宅後",
      active: true,
    },
    {
      id: "commute-am",
      weekday: 2,
      startTime: "07:20",
      endTime: "08:05",
      context: "mobile",
      focusLevel: "medium",
      extendable: false,
      label: "往路通学",
      active: true,
    },
    {
      id: "evening-desk",
      weekday: 2,
      startTime: "19:10",
      endTime: "21:50",
      context: "desk",
      focusLevel: "high",
      extendable: true,
      label: "帰宅後",
      active: true,
    },
    {
      id: "weekend-main",
      weekday: 6,
      startTime: "10:00",
      endTime: "12:00",
      context: "desk",
      focusLevel: "high",
      extendable: false,
      label: "土曜午前",
      active: true,
    },
  ],
  exceptions: [
    {
      id: "club-overrun",
      date: "2026-08-11",
      type: "capacity_delta",
      deltaMinutes: -35,
      note: "部活延長",
    },
    {
      id: "hard-stop",
      date: "2026-08-11",
      type: "hard_stop_override",
      endAt: "21:30",
      note: "翌朝が早い",
    },
  ],
  materials: [
    {
      id: "math-probability",
      subject: "数学",
      name: "確率・証明演習",
      phase: "初見",
      unitType: "題",
      startValue: 1,
      endValue: 42,
      currentValue: 12,
      deadline: "2026-08-20",
      subjectPriority: 5,
      materialPriority: 5,
      context: "desk",
      minChunk: 2,
      initialMinutesPerUnit: 18,
      estimatedMinutesPerUnit: 16,
      active: true,
    },
    {
      id: "chem-calc",
      subject: "化学",
      name: "理論計算セット",
      phase: "復習",
      unitType: "題",
      startValue: 1,
      endValue: 36,
      currentValue: 20,
      deadline: "2026-08-18",
      subjectPriority: 4,
      materialPriority: 4,
      context: "desk",
      minChunk: 2,
      initialMinutesPerUnit: 14,
      estimatedMinutesPerUnit: 12,
      active: true,
    },
    {
      id: "english-words",
      subject: "英語",
      name: "英単語ターゲット",
      phase: "復習",
      unitType: "語",
      startValue: 1,
      endValue: 900,
      currentValue: 620,
      deadline: "2026-08-31",
      subjectPriority: 4,
      materialPriority: 3,
      context: "mobile",
      minChunk: 30,
      initialMinutesPerUnit: 0.35,
      estimatedMinutesPerUnit: 0.3,
      active: true,
    },
    {
      id: "world-history",
      subject: "世界史",
      name: "近現代史確認",
      phase: "復習",
      unitType: "ページ",
      startValue: 1,
      endValue: 80,
      currentValue: 48,
      deadline: "2026-08-24",
      subjectPriority: 3,
      materialPriority: 4,
      context: "mobile",
      minChunk: 4,
      initialMinutesPerUnit: 3,
      estimatedMinutesPerUnit: 2.5,
      active: true,
    },
  ],
  existingTasks: [
    {
      id: "locked-math",
      date: "2026-08-10",
      slotId: "2026-08-10:evening-desk",
      materialId: "math-probability",
      materialName: "確率・証明演習",
      subject: "数学",
      rangeStart: 12,
      rangeEnd: 14,
      unitType: "題",
      minimumQty: 2,
      standardQty: 2,
      extraQty: 2,
      actualQty: 0,
      estimatedMinutes: 32,
      status: "planned",
      achievement: "none",
      locked: true,
      revision: 1,
      startAt: "2026-08-10T19:20:00.000Z",
      endAt: "2026-08-10T21:40:00.000Z",
    },
  ],
};
